### PR TITLE
add empty py312+ package

### LINKED ISSUE #3: Make it empty for python >= 3.12
Given commit https://github.com/conda-forge/backports.strenum-feedstock/commit/7d0d99c3c5b97f7cfe754b0317cb332de4f4c261, I wonder if we should apply the "empty package pattern" as documented at https://conda-forge.org/docs/maintainer/knowledge_base/#empty-python-packages.

This means that for Python 3.12+, the package would be empty, but would allow easier integration with noarch packages downstream.

xref https://github.com/conda-forge/conda-smithy/pull/1883

### PR DESCRIPTION
**Pull request by jaimergp**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Closes #3

### CODE REVIEW

**Comment by jakirkham** [comment]
Thanks Jaime! 🙏

Somewhat unrelated. Should this package depend on [`backports`]( https://github.com/conda-forge/backports-feedstock )?

**Comment by jaimergp** [comment]
For `noarch packages can't have selectors`... I guess Jinja it is 🤷 


> Somewhat unrelated. Should this package depend on [backports](https://github.com/conda-forge/backports-feedstock)?

Probably? I'll add it.

**Comment by jakirkham** [comment]
We've softened the linter constraint some for the `noarch` selector use case. Maybe we can soften that more

**Comment by jaimergp** [comment]
```
{
  "backports.strenum-1.3.1-pyh039bcf3_1.conda": {
    "recipe": {
      "build_type": "regular",
      "channel_targets": "conda-forge main"
    }
  }
}
---
{
  "backports.strenum-1.3.1-haf276df_1.conda": {
    "recipe": {
      "build_type": "empty",
      "channel_targets": "conda-forge main"
    }
  }
}
```

Different hashes, so I think we are good 🚀 

I'll add an issue for the linter.

@tadeu - this is ready for review, thanks!

**Comment by jaimergp** [comment]
Also mostly a note to self, once this goes in, it would be good to add it to the [docs table](https://conda-forge.org/docs/maintainer/knowledge_base/#empty-python-packages).

**Review by tadeu — APPROVED** [review]
TIL about https://conda-forge.org/docs/maintainer/knowledge_base/#empty-python-packages, thanks @jaimergp!

**Comment by hmaarrfk** [comment]
Just FYI, this build had catastrophically failed (failed to pull from quay.io) so I had to restart the build just now.

**Comment by hmaarrfk** [comment]
packages now seem to be uploaded.

**Pull request merged**
